#!/usr/bin/env python2

#Created on Wed May 6 12:45:37 2018

#handler for cron to run ebam_getdata.py and retrieve the ebam hourly data, saving to a file

#@author: Marissa

from datetime import datetime, timedelta
from ebam_getdata import getEbamLastHour
import pandas as pd

now=datetime.now()
yesterday=now-timedelta(days=1)

#name the file based on today's date
fn='/home/lar/ebam-plus/src/EBAM_' + now.strftime ('%Y%m%d')+'.csv'

#at hour 0 start a new file with a new header, at other hours just open the existing file
#also find the time of the previous entry saved to use for checking errors (for hour 0 this is yesterday's file)
if now.hour==0:
    f=open(fn,'w+')
    f.write('Time,ConcRT(ug/m3),ConcHR(ug/m3),Flow(lpm),WS(m/s),WD(Deg),AT(C),RH(%),BP(mmHg),FT(C),FRH(%),BV(V),PM,Status\n')
    yesterdayfn='/home/lar/ebam-plus/src/EBAM_' + yesterday.strftime ('%Y%m%d')+'.csv'
    df=pd.read_csv(yesterdayfn, parse_dates=True, index_col='Time')
    last_time=df.index[-1]
else:
    f=open(fn, 'a+')
    df=pd.read_csv(fn, parse_dates=True, index_col='Time')
    last_time=df.index[-1]

#use getEbamLastHour get have the pi make a serial port connection to the EBAM, get the most recent data, and return one line with the most recent hour
hourline=getEbamLastHour()

#find the time of the current entry to use for checking errors
dfnew=pd.read_csv('temp.csv', parse_dates=True, index_col='Time')
new_time=dfnew.index[-1]

#write the data from the last hour, checking that the current time is different from the last time saved and is one hour later
if new_time!=last_time:
    f.write(hourline)
    f.write('\n')
    print('New hour saved successfully.')
    if new_time-timedelta(hours=1)!=last_time:
        print("Error: Data are not one hour apart. Check whether some data was missed.")
else:
    print("Error: Unexpected time. New time is the same as previous time.")


f.close()

